##############################################################################
# make file for MainProgramTest1FOCS.f90
#############################################################################

# Compiler
#FC = ifort
FC = gfortran

# Compiler options
FCflags = -O0 -fdefault-double-8 -fdefault-real-8 #-g3 -fbacktrace -fbounds-check #-ffpe-trap=denormal,inexact,invalid,zero,underflow,overflow
#FCflags = -O3 -init=zero -ipo -align -fp-model fast=2 -real-size 64

# Fortran source files from LAPACK needed to solve the coarse grid system
# directly using LU factorization
SRC_LU = ./LinearSolver/dgemm.f\
	./LinearSolver/dgesv.f\
	./LinearSolver/dgetrf.f\
	./LinearSolver/dgetrf2.f\
	./LinearSolver/dgetrs.f\
	./LinearSolver/dlamch.f\
	./LinearSolver/dlaswp.f\
	./LinearSolver/dscal.f\
	./LinearSolver/dtrsm.f\
	./LinearSolver/idamax.f\
	./LinearSolver/ieeeck.f\
	./LinearSolver/ilaenv.f\
	./LinearSolver/iparmq.f\
	./LinearSolver/lsame.f\
	./LinearSolver/xerbla.f

# Fortran source files for the FOCS
SRC = ./GeneralSubroutines/FOCS2DSpecifyPrecision.f90\
	./GeneralSubroutines/FOCS2DConstants.f90\
	./GeneralSubroutines/FOCS2DSettings.f90\
	./TestProblems/TestProblem1.f90\
	./GeneralSubroutines/FOCS2DDataStructures.f90\
	./GeneralSubroutines/FOCS2DMiscellaneous.f90\
	./GeometricMultigrid/FOCS2DCoarseGridSolver.f90\
	./GeometricMultigrid/FOCS2DMatvecs.f90\
	./GeometricMultigrid/FOCS2DRestrictionOperator.f90\
	./GeometricMultigrid/FOCS2DInterpolationOperator.f90\
	./GeometricMultigrid/FOCS2DSmoother.f90\
	./GeometricMultigrid/FOCS2DMultigridCycle.f90\
	./GeometricMultigrid/FOCS2DFastPoissonSolver.f90\
	./mainPrograms/MainProgramTest1FOCS.f90

# object codes from dfftpack
OBJ_LU = dgemm.o\
	dgesv.o\
	dgetrf.o\
	dgetrf2.o\
	dgetrs.o\
	dlamch.o\
	dlaswp.o\
	dscal.o\
	dtrsm.o\
	idamax.o\
	ieeeck.o\
	ilaenv.o\
	iparmq.o\
	lsame.o\
	xerbla.o

# object files for main codes
OBJ = FOCS2DSpecifyPrecision.o\
	FOCS2DConstants.o\
	FOCS2DSettings.o\
	TestProblem1.o\
	FOCS2DDataStructures.o\
	FOCS2DMiscellaneous.o\
	FOCS2DCoarseGridSolver.o\
	FOCS2DMatvecs.o\
	FOCS2DRestrictionOperator.o\
	FOCS2DInterpolationOperator.o\
	FOCS2DSmoother.o\
	FOCS2DMultigridCycle.o\
	FOCS2DFastPoissonSolver.o\
	MainProgramTest1FOCS.o

# All Modules listed
MODULES = FOCS2DConstants.mod\
	FOCS2DSpecifyPrecision.mod\
	FOCS2DSettings.mod\
	TestProblem1.mod\
	FOCS2DDataStructures.mod\
	FOCS2DMiscellaneous.mod\
	FOCS2DCoarseGridSolver.mod\
	FOCS2DMatvecs.mod\
	FOCS2DRestrictionOperator.mod\
	FOCS2DInterpolationOperator.mod\
	FOCS2DSmoother.mod\
	FOCS2DMultigridCycle.mod\
	FOCS2DFastPoissonSolver.mod\

exec: $(OBJ) libLU.a
	$(FC) $(FCflags) -o exec $(OBJ) libLU.a

$(OBJ): $(SRC) libLU.a
	$(FC) $(FCflags) -c $(SRC)

$(OBJ_LU): $(SRC_LU)
	$(FC) $(FCflags) -c $(SRC_LU)

libLU.a: $(SRC_LU)
	$(FC) $(FCflags) -c $(SRC_LU)
	ar cr libLU.a $(OBJ_LU)
	rm $(OBJ_LU)

# This should delete all the executable file generated by the makefile
clean:
	rm *.o *.a *.mod exec
